services:
  app_auth:
    build:
      dockerfile: Docker-build/auth/Dockerfile
      context: .
    working_dir: /auth
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB_AUTH}
    ports:
      - "${APP_AUTH_PORT}:${CONTAINER_AUTH_PORT}"
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./auth
          target: /app_auth
        - action: rebuild
          path: auth/poetry.lock

  catalogs_services:
    build:
      dockerfile: Docker-build/catalog/Dockerfile
      context: .
    working_dir: /catalogs_services
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB_CATALOG}
    ports:
      - "${APP_CATALOG_PORT}:${CONTAINER_CATALOG_PORT}"
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./catalogs_services
          target: /catalogs_services
        - action: rebuild
          path: catalogs_services/poetry.lock

  orders_service:
    build:
      dockerfile: Docker-build/order/Dockerfile
      context: .
    working_dir: /orders_service
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB_ORDER}
    ports:
      - "${APP_ORDER_PORT}:${CONTAINER_ORDER_PORT}"
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./orders_service
          target: /orders_service
        - action: rebuild
          path: orders_service/poetry.lock

  pg:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis_julyberries
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  kafka:
    image: bitnami/kafka:3.5.0
    container_name: kafka1
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:19093,2@kafka2:19093,3@kafka3:19093
      - KAFKA_KRAFT_CLUSTER_ID=puBRtLWlQRqO6T7ZbW7ztw
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - kafka-net

  kafka2:
    image: bitnami/kafka:3.5.0
    container_name: kafka2
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:19093,2@kafka2:19093,3@kafka3:19093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=puBRtLWlQRqO6T7ZbW7ztw
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9093:9092"
    networks:
      - kafka-net

  kafka3:
    image: bitnami/kafka:3.5.0
    container_name: kafka3
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:19093,2@kafka2:19093,3@kafka3:19093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=puBRtLWlQRqO6T7ZbW7ztw
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9094:9092"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  pgdata:
  redis_data: