"""fix column access token

Revision ID: 531ccec2fb46
Revises: f723b935f57d
Create Date: 2025-08-22 00:02:07.101905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "531ccec2fb46"
down_revision: Union[str, Sequence[str], None] = "f723b935f57d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "access_tokens",
        "token",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "access_tokens",
        "token",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
