"""update table order and oreritem

Revision ID: 2d323db2d3a5
Revises: fa3590a7ea06
Create Date: 2025-09-19 14:48:26.847802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d323db2d3a5"
down_revision: Union[str, Sequence[str], None] = "fa3590a7ea06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_order_items_order_id_orders"),
        "order_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_order_items_order_id_orders"),
        "order_items",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_order_items_order_id_orders"),
        "order_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_order_items_order_id_orders"),
        "order_items",
        "orders",
        ["order_id"],
        ["id"],
    )
    # ### end Alembic commands ###
