[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python="^3.13.5"
motor = "^3.7.1"
beanie = "^2.0.0"
pymongo = "^4.15.1"
pydantic-settings = "^2.11.0"
fastapi = "^0.117.1"
uvicorn = "^0.37.0"
httpx = "^0.28.1"


[dependency-groups]
dev = [
    "black (>=25.9.0,<26.0.0)"
]
