{
 "title": "auth Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(auth_requests_total,app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(auth_requests_total{app_name=\"$app_name\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_request_duration_seconds_sum{app_name=\"$app_name\"} / auth_request_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(auth_request_duration_seconds_bucket{app_name=\"$app_name\", path!=\"/metrics\"}[1m])) by(path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(auth_requests_total{app_name=\"$app_name\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Log of All http App",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker-logs\", container_name=\"app_auth\"} | json | line_format \"{{.log}}\""
    }
   ]
  }
 ]
}